//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_Meeting
    {
        public int MID { get; set; }
        public string MName { get; set; }
        public Nullable<System.DateTime> MTime { get; set; }
        public string MAudioSituation { get; set; }
        public string MText { get; set; }
        public string Mspeak { get; set; }
        public string Mhealth { get; set; }
        public Nullable<System.DateTime> Mstart { get; set; }
        public Nullable<System.DateTime> MOwer { get; set; }
        public string MSolve { get; set; }
        public string MNote { get; set; }
        public Nullable<System.DateTime> MOpenTime { get; set; }
        public string MConference { get; set; }
        public string MUserName { get; set; }
        public string MOpinion { get; set; }
        public string Msignature { get; set; }
        public Nullable<System.DateTime> MOverTime { get; set; }
        public string MComments { get; set; }
        public string closeDevice { get; set; }
        public Nullable<int> QZ { get; set; }
    }
}
