//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(IsReference =true)]
    public partial class info_Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public info_Asset()
        {
            this.info_Equipment = new HashSet<info_Equipment>();
        }
        [DataMember]
        public int AID { get; set; }
        [DataMember]
        public string AName { get; set; }
        [DataMember]
        public int ATypeId { get; set; }
        [DataMember]
        public string AModel { get; set; }
        [DataMember]
        public Nullable<decimal> AMoney { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ABuyTime { get; set; }
        [DataMember]
        public Nullable<System.DateTime> ApplyTime { get; set; }
        [DataMember]
        public string AParameter { get; set; }
        [DataMember]
        public string ASuppler { get; set; }
        [DataMember]
        public string AEM { get; set; }
        [DataMember]
        public string RealName { get; set; }
        [DataMember]
        public Nullable<int> JID { get; set; }
        [DataMember]
        public Nullable<int> SID { get; set; }
        [DataMember]
        public string ARemarks { get; set; }
        [DataMember]
        public Nullable<int> TID { get; set; }
        [DataMember]
        public Nullable<int> CRelustID { get; set; }
        [DataMember]
        public string AYears { get; set; }
        [DataMember]
        public string AExplain { get; set; }
        [DataMember]
        public string ASupplerPhone { get; set; }
        [DataMember]
        public string AShenHeRan { get; set; }
        [DataMember]
        public string AShenHeYiJian { get; set; }
        [DataMember]
        public string AShenHeJieGuo { get; set; }
        [DataMember]
        public string AShenHeRiQi { get; set; }
    
        public virtual CaiGouXingShi CaiGouXingShi { get; set; }
        public virtual CaiGouYiJu CaiGouYiJu { get; set; }
        public virtual PiShiJieGuo PiShiJieGuo { get; set; }
        public virtual ZiChanBeiZhu ZiChanBeiZhu { get; set; }
        public virtual ZiChanZhuangTai ZiChanZhuangTai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<info_Equipment> info_Equipment { get; set; }
    }
}
