//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_Equipment
    {
        public int EID { get; set; }
        public string EDeviceName { get; set; }
        public string EquipmentModel { get; set; }
        public string Eoffice { get; set; }
        public string Ebusinesssystem { get; set; }
        public Nullable<System.DateTime> EbuYTime { get; set; }
        public string Eyear { get; set; }
        public string Eversion { get; set; }
        public string DEetailedParameters { get; set; }
        public string Esupplier { get; set; }
        public string EPhone { get; set; }
        public string Econtact { get; set; }
        public string EIP { get; set; }
    }
}
