//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_Registration
    {
        public int RID { get; set; }
        public string RName { get; set; }
        public Nullable<int> SID { get; set; }
        public string RUserId { get; set; }
        public string ROffice { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
        public string RFunction { get; set; }
        public string Requirements { get; set; }
        public string Rdepartment { get; set; }
        public string RInformationCenter { get; set; }
        public string RState { get; set; }
        public string Remaek { get; set; }
        public Nullable<int> IsOk { get; set; }
    
        public virtual info_Software info_Software { get; set; }
    }
}
