//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class info_ComputerRoomVisit
    {
        public int CID { get; set; }
        public string CName { get; set; }
        public Nullable<System.DateTime> CTIme { get; set; }
        public string Cause { get; set; }
        public string Carries { get; set; }
        public Nullable<int> CEntourage { get; set; }
        public string CBringOut { get; set; }
        public Nullable<System.DateTime> CEntryTime { get; set; }
        public Nullable<System.DateTime> CLeaveTime { get; set; }
        public string CRegistar { get; set; }
        public string CInstructor { get; set; }
        public int CRelustID { get; set; }
        public Nullable<System.DateTime> CInstructorTime { get; set; }
        public string COpinion { get; set; }
        public Nullable<int> CXuanXiang { get; set; }
    
        public virtual PiShiJieGuo PiShiJieGuo { get; set; }
    }
}
