//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Asset
    {
        public int AID { get; set; }
        public string AName { get; set; }
        public string ATypeId { get; set; }
        public string AModel { get; set; }
        public Nullable<decimal> AMoney { get; set; }
        public Nullable<System.DateTime> ABuyTime { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string AParameter { get; set; }
        public string ASuppler { get; set; }
        public string AEM { get; set; }
        public string RealName { get; set; }
        public Nullable<int> JID { get; set; }
        public Nullable<int> SID { get; set; }
        public string ARemarks { get; set; }
        public string TID { get; set; }
        public string CRelustID { get; set; }
        public string AYears { get; set; }
        public string AExplain { get; set; }
    }
}
