//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_info_Technology
    {
        public int TID { get; set; }
        public string TSerialNumber { get; set; }
        public string SID { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public string TUserId { get; set; }
        public Nullable<System.DateTime> TRegistrationTiime { get; set; }
        public string TConsultant { get; set; }
        public string TDepartment { get; set; }
        public string Tcontact { get; set; }
        public string QID { get; set; }
        public string TDescribe { get; set; }
        public string TAnswer { get; set; }
        public string TAnswerTime { get; set; }
        public string TRemark { get; set; }
    }
}
